server:
  port: 8082
spring:
  application:
    name: "CrediYa"
  devtools:
    restart:
      enabled: false
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
aws:
  region: "us-east-1"
  dynamodb:
    endpoint: ${APPROVED_LOANS_DYNAMO_TABLE}
    tables:
      approved-loans: ${APPROVED_LOANS_DYNAMO_TABLE}
entrypoint:
  sqs:
    region: "us-east-1"
    queueUrl: "${LOAN_APPLICATION_APPROVED_QUEUE}"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

security:
  jwt:
    secret: "${JWT_SECRET}"
